# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd03e6b49bc1b8d493894a7fe8a7a3bd26e993434306eed264bd361f04cdcb102b5f6a7d2e00489745756eae6b92cc2091071695cbe723133fdb8ff5536f2042

test:
  secret_key_base: 061ff9a4f767fb0c162a813384d382cd3fa42ab79604a43a603903ed2b3afbca9e81f7f91b97bd7e5180eeb77ceafad0a37f435df8dceaeab4b7a191ba3471c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
